DNSの自動デプロイ
sohosai/infrastructure pull request #24
Opened 2023-09-04 10:40 UTC by appare45

close #1 

- DNSを設定
- DNSに関するドキュメントを整備

2023-09-15 09:52 UTC, momeemt requested changes
確認をお願いします

2023-09-15 09:52 UTC, momeemt commented on dns.tf
> +  zone_id = "473405a99e276061eee7da4bef87aa3e"
zone_idは `var.cloudflare_zone_id` から取ってください

2023-09-15 09:52 UTC, momeemt commented on dns.tf
> +  zone_id = "473405a99e276061eee7da4bef87aa3e"
そのほかのzone_idについても同様にお願いします

2023-09-15 10:13 UTC, appare45 commented on dns.tf
> +  zone_id = "473405a99e276061eee7da4bef87aa3e"
修正しました

2023-09-22 10:09 UTC, momeemt approved these changes
LGTM!

2023-09-22 10:09 UTC, merged